### ISSUE TITLE
Help Request: Moving HTMLY-Blog from offline to online (change location)

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#171]
I first worked offline with HTMLY through EasyPHP (similar software like XAMPP) to manage the page. Now as I'm quite ready to put in online, I changed the parameter **site.url** in the **config.ini** to the URL of the new place where i put my website.
Now of course i need to clear the cache in order to update all the links which still point to **localhost/somefolder/somefolder/...** - and there occurs the problem. I cannot log in to the admin-page and i get the following error:

**Fatal error: Call to undefined function password_verify() in /home/u151238773/public_html/system/admin/admin.php on line 54**

Now I don't know what to do...

Thanks in advance,
Greetings

**Comment by danpros** [comment]
Hello,

Seems you are using old version. Download the latest version here https://github.com/danpros/htmly/releases/tag/v2.5.4

**Comment by gesundelehre** [comment]
Ok, I try to - I modified some files myself though. So I need to make the changes again to the files.

But thanks for the info - I'll use the new version then.

**Comment by danpros** [comment]
Please try new htmly version (master branch on the new dev site) on the local host and give me the feedback. There are a few changes and will release it soon but I will try to replace current theme first

**Comment by gesundelehre** [comment]
Ok, i download the most up-to-date master and try to use it locally first. Afterwards i'll give you a feedback. Thank you anyway for all your efforts!

**Comment by gesundelehre** [comment]
- ok one thing that seems to need improvement at the current master-version: When I add a new regular blog post > save it as a draft > afterwards click on edit that same draft  > then want to publish that same draft > then there is a required video-field. That video field should not be a required field, as not all posts will contain videos.

I'll be continuing testing

**Comment by danpros** [comment]
@gesundelehre thanks for the report :smile: I will check it.

The idea is like a Tumblr blog that have a few content type. Just testing to convert html template to htmly template https://goo.gl/t5mVd6

**Comment by gesundelehre** [comment]
@danpros please wait, it seems there are more bugs

**Comment by danpros** [comment]
@gesundelehre just committing the changes, please check it, please use the master branch.

**Comment by gesundelehre** [comment]
##BUG REPORT from the latest master i downloaded (i downloaded it at about 18:00 on 2015-07-20)

Ok, next things that could need improvement:

1) create new regular post > save as draft (filename of draft is in format Y-m-d H:i:s) > open that draft > update draft (filename is in format Y-m-d h:i:s ---> the format changed from "H" to "h", meaning from a 24-hour format to a 12-hour format which results in that the sorting order of the posts will be corrupt...)
2) create new regular post > save as draft (filename of draft is in format Y-m-d H:i:s) > open that draft > publish draft > the filename format is being changed as well to a 12-hour format
3) same as nr 1 happens with if i add a new image featured post the format changes to 12hour (actually the time is loaded correctly into the form to edit the draft, but afterwards if I update the draft, the time is saved falsely)
4) the same as nr 2 happens if i want to add an image-featured post -> somehow it seems that all these forms are corrupt... (also if i want to add a quote and bypass the draft mode, it changes to the 12hour-format)
5) if i want to add a featured link post - in the title of the editor there is written <title>add video</title> instesad of link
6) add featured link > save as draft > edit that draft > save draft again (update it) > edit draft again --> now the link to the featured link disappeared!! Instead of that, there is an empty box where one can put a link to a video -> instead of the link...
7) Subpages don't show up in menu (is this a bug? Maybe it would be nice to show the subpages in the menu only when the parent page to this subpage have been clicked on - or it could be specified a value in the config.ini to specify this behaviour)

**Comment by danpros** [comment]
For point 1-4 I will try to debug it tomorrow.

Point 5-6 should has been fixed by latest commit a moment ago.

Point 7. I am temporary disabling it using css since its need more styling. Well simple dropdown menu is enough.

**Comment by gesundelehre** [comment]
Could you tell me, when the master is usable again - because I'd like to use it asap for my online website

**Comment by danpros** [comment]
@gesundelehre please check the latest commits. I already fix the date time problems and report back if you still found any problems with it.

**Comment by gesundelehre** [comment]
@danpros date problem still there. Date still get changed to 12-hours-format if I save it first as draft and then publish the draft

**Comment by gesundelehre** [comment]
Ok, Nr 1-6 are now working - Bugs fixed
Could you please inform me, when the css-menu with submenu-items is working? Its essential for my website... Otherwise I can't use it... Thnx in advance
